# Generated by Django 4.2.2 on 2023-06-13 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='description',
            field=models.CharField(default='SOME STRING'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='name',
            field=models.CharField(default='SOME STRING'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='name',
            field=models.CharField(default='SOME STRING'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='material',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
