# Generated by Django 4.2.2 on 2023-06-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_description_inventory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='description',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(default=''),
        ),
    ]
