# Generated by Django 4.2.2 on 2023-06-13 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_description_alter_inventory_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='inventory',
        ),
        migrations.AddField(
            model_name='inventory',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Material', to='inventory.material'),
        ),
    ]
