# Generated by Django 4.2.2 on 2023-06-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_material_inventory_inventory_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='sku',
        ),
    ]
