# Generated by Django 4.2.2 on 2023-06-13 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0006_inventory_user_material_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryoperations',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserOperation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventoryoperations',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MaterialOperation', to='inventory.material'),
        ),
    ]
