# Generated by Django 4.2.2 on 2023-06-13 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventoryoperations_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryoperations',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='InventoryOperation', to='inventory.inventory'),
        ),
    ]
