# Generated by Django 4.2.2 on 2023-06-13 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0009_alter_inventory_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='description',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='MaterialInventory', to='inventory.material'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='UserInventory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventoryoperations',
            name='operation',
            field=models.CharField(verbose_name=[('ADDINVENTORY', 'Addinventori'), ('SUBTRACTINVENTORY', 'Subtractiventori'), ('ADDMATERIAL', 'Addmaterial'), ('SUBTRACTMATERIAL', 'Subtract')]),
        ),
        migrations.AlterField(
            model_name='inventoryoperations',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='inventoryoperations',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='UserOperation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='material',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
