# Generated by Django 4.2.2 on 2023-06-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_inventory_description_alter_inventory_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryoperations',
            name='operation',
            field=models.CharField(verbose_name=[('ADDINVENTORY', 'Addinventori'), ('SUBTRACTINVENTORY', 'Subtractiventori'), ('ADDMATERIAL', 'Addmaterial'), ('SUBTRACTMATERIAL', 'Subtractmaterial')]),
        ),
    ]
