# Generated by Django 4.2.2 on 2023-06-15 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_inventory_sku_alter_inventory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryoperations',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
