# Generated by Django 4.2.2 on 2023-06-15 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_inventoryoperations_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='inventory.material'),
        ),
    ]
